version: 2
jobs:
  py2-build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-py2-dependencies-{{ checksum "requirements.txt" }}
          - v1-py2-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install --user virtualenv
            python -m virtualenv venv2
            . venv2/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv2
          key: v1-py2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv2/bin/activate
            pytest .

      - store_artifacts:
          path: test-reports
          destination: test-reports

  py3-build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-py3-dependencies-{{ checksum "requirements.txt" }}
          - v1-py3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv3
            . venv3/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv3
          key: v1-py3-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv3/bin/activate
            pytest .

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  python2&3:
    jobs:
      - py2-build
      - py3-build

